import '@/styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: React.ReactNode
}

export default function RootLayout(props: Props) {
  const {children} = props
  return (
    <html lang="ua">
      <body>{children}</body>
    </html>
  )
}
