/* eslint-disable max-lines-per-function */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/dolphin2.glb --transform --types --resolution 1024
Files: public/dolphin.glb [59.49KB] > /dolphin.glb [22.38KB] (62%)
*/
import {useAnimations, useGLTF} from '@react-three/drei'
import {useGraph} from '@react-three/fiber'
import {useEffect, useMemo, useRef} from 'react'
import {
  AnimationClip,
  Bone,
  Group,
  Mesh,
  MeshStandardMaterial,
  SkinnedMesh
} from 'three'
import {GLTF, SkeletonUtils} from 'three-stdlib'
import {ActionNameDolphin} from './model-helpers'

interface GLTFAction extends AnimationClip {
  name: ActionNameDolphin
}

type GLTFResult = GLTF & {
  nodes: {
    Dolphin_1: SkinnedMesh
    Dolphin_2: SkinnedMesh
    Root: Bone
  }
  materials: {
    Top: MeshStandardMaterial
    Bottom: MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export const DolphinModel = () => {
  const group = useRef<Group>(null)
  const {scene, animations} = useGLTF('/dolphin.glb')
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
  const {nodes, materials} = useGraph(clone) as unknown as GLTFResult
  const {actions} = useAnimations(animations, group)

  useEffect(() => {
    const action = actions['Swim']
    if (action) {
      action.reset().fadeIn(0.5).play()
      return () => {
        action.fadeOut(0.5)
      }
    }
  }, [actions])

  useMemo(() => {
    scene.traverse(child => {
      if (
        child instanceof Mesh &&
        child.material instanceof MeshStandardMaterial
      ) {
        const material = child.material

        material.onBeforeCompile = shader => {
          // adding uniforms
          shader.uniforms.uWaterLevel = {value: 0.0}
          shader.uniforms.uUnderWaterDarkness = {value: 0.2}
          shader.uniforms.uTransitionSmoothness = {value: 0.5}

          // shader modification
          shader.vertexShader = `
          varying vec3 vWorldPosition;
          ${shader.vertexShader}
        `.replace(
            '#include <worldpos_vertex>',
            `#include <worldpos_vertex>
           vWorldPosition = (modelMatrix * vec4(transformed, 1.0)).xyz;`
          )

          shader.fragmentShader = `
          uniform float uWaterLevel;
          uniform float uUnderWaterDarkness;
          uniform float uTransitionSmoothness;
          varying vec3 vWorldPosition;
          ${shader.fragmentShader}
        `.replace(
            '#include <dithering_fragment>',
            `#include <dithering_fragment>
           float mixFactor = smoothstep(uWaterLevel - uTransitionSmoothness, uWaterLevel, vWorldPosition.y);
           float finalDarkness = mix(uUnderWaterDarkness, 1.0, mixFactor);
           gl_FragColor.rgb *= finalDarkness;
           vec3 waterTint = vec3(0.0, 0.2, 0.4);
           gl_FragColor.rgb = mix(mix(gl_FragColor.rgb, waterTint, 0.3), gl_FragColor.rgb, mixFactor);`
          )
        }
        material.needsUpdate = true
      }
    })
  }, [scene])

  return (
    <group ref={group} dispose={null} castShadow receiveShadow>
      <group name="Scene">
        <group name="Armature" position={[0, 0.533, 0]}>
          <primitive object={nodes.Root} />
        </group>
        <group name="Dolphin" position={[0, 0.533, 0]}>
          <skinnedMesh
            name="Dolphin_1"
            geometry={nodes.Dolphin_1.geometry}
            material={materials.Top}
            skeleton={nodes.Dolphin_1.skeleton}
          />
          <skinnedMesh
            name="Dolphin_2"
            geometry={nodes.Dolphin_2.geometry}
            material={materials.Bottom}
            skeleton={nodes.Dolphin_2.skeleton}
          />
        </group>
      </group>
    </group>
  )
}
